### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by joshstoik1** [mmtrt/WINE_AppImage#24]
Hi there,

I have been using the stable and staging AppImages successfully for a while now on Ubuntu Lunar, but after updating to the builds from two days ago, they no longer work. I'm getting errors like:

```
./wine-stable_8.0.1-x86_64.AppImage 
/tmp/.mount_wine-sMJofDn/wrapper: line 77: /tmp/.mount_wine-sMJofDn/usr/bin/wine: No such file or directory
```

Is that related to the wrapper script changes, do you think?

**Comment by mmtrt** [comment]
~~That should be due to this change c014dd20f51194989b4d97dcf549501738597fe7 and its failing for you due to missing `libc6:i386` from your system probably & appimage have lower version of libc6 then host due to change above.~~

~~Although can you test wow64 builds see if these work.~~

~~Also test this [build](https://github.com/mmtrt/WINE_AppImage/releases/tag/test3) have force libc6 version to lunar not sure that will work but I've just added hack change.~~
